name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run deploy script
        run: |
          git config user.name "atomic-variable" && git config user.email "saranya70388@gmail.com"
          pnpm run gh-pages-deploy
